# UK Logistics & Road Freight Intelligence Dashboard

## Notebook 01: Data Understanding

This notebook is the first stage of the UK Logistics & Road Freight Intelligence Dashboard project.

The purpose of this notebook is to:

- Inspect the downloaded Department for Transport data files
- Identify available road freight and road traffic datasets
- Review file types, names and structures
- Inspect CSV and ODS files
- Check columns, rows and sheet names
- Understand which datasets are suitable for cleaning, SQL analysis and Power BI reporting

At this stage, no cleaning or transformation is being performed. The focus is only on understanding the raw data structure.

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np
import os

In [3]:
# Define project paths

raw_data_path = Path("../data/raw")
processed_data_path = Path("../data/processed")

print("Raw data folder exists:", raw_data_path.exists())
print("Processed data folder exists:", processed_data_path.exists())

Raw data folder exists: True
Processed data folder exists: True

In [4]:
# List all files in the raw data folder

raw_files = sorted([file for file in raw_data_path.iterdir() if file.is_file()])

for file in raw_files:
    print(file.name)

.gitkeep
local_authority_traffic.csv
region_traffic_by_road_type.csv
region_traffic_by_vehicle_type.csv
rfs0101.ods
rfs0121.ods
rfs0122.ods
rfs0125.ods

In [5]:
# Create file inventory

file_inventory = []

 for_file_list = []

for file in raw_files:
    file_inventory.append({
        "file_name": file.name,
        "file_extension": file.suffix.lower(),
        "file_size_mb": round(file.stat().st_size / (1024 * 1024), 2)
    })

file_inventory_df = pd.DataFrame(file_inventory)

file_inventory_df

IndentationError: unexpected indent (2242382727.py, line 5)

In [6]:
# Create file inventory

file_inventory = []

for file in raw_files:
    file_inventory.append({
        "file_name": file.name,
        "file_extension": file.suffix.lower(),
        "file_size_mb": round(file.stat().st_size / (1024 * 1024), 2)
    })

file_inventory_df = pd.DataFrame(file_inventory)

file_inventory_df

                            file_name file_extension  file_size_mb
0                            .gitkeep                         0.00
1         local_authority_traffic.csv           .csv          0.43
2     region_traffic_by_road_type.csv           .csv          0.10
3  region_traffic_by_vehicle_type.csv           .csv          0.04
4                         rfs0101.ods           .ods          0.01
5                         rfs0121.ods           .ods          0.01
6                         rfs0122.ods           .ods          0.01
7                         rfs0125.ods           .ods          0.01

In [7]:
# Count file types

file_inventory_df["file_extension"].value_counts()

file_extension
.ods    4
.csv    3
        1
Name: count, dtype: int64

## Inspect CSV Files

This section previews the downloaded CSV files so that I can understand their column structure, row counts and suitability for analysis.

In [8]:
# Inspect CSV files

csv_files = [file for file in raw_files if file.suffix.lower() == ".csv"]

print("CSV files found:", len(csv_files))

for file in csv_files:
    print("\n" + "=" * 80)
    print("File:", file.name)
    print("=" * 80)
    
    try:
        df_preview = pd.read_csv(file, nrows=5, low_memory=False)
        df_full_sample = pd.read_csv(file, nrows=1000, low_memory=False)
        
        print("Preview shape:", df_preview.shape)
        print("Columns:")
        print(df_preview.columns.tolist())
        display(df_preview.head())
        
    except Exception as error:
        print("Could not read file:", file.name)
        print("Error:", error)

CSV files found: 3

================================================================================
File: local_authority_traffic.csv
================================================================================
Preview shape: (5, 8)
Columns:
['local_authority_id', 'local_authority_name', 'local_authority_code', 'year', 'link_length_km', 'link_length_miles', 'cars_and_taxis', 'all_motor_vehicles']

,local_authority_id,local_authority_name,local_authority_code,year,link_length_km,link_length_miles,cars_and_taxis,all_motor_vehicles
0,1,Isles of Scilly,E06000053,1993,36.01,22.38,9.000000e+05,1400000
1,2,Nottinghamshire,E10000024,1993,4650.69,2889.80,2.702600e+09,3368900000
2,3,Glasgow City,S12000049,1993,1768.54,1098.92,1.381200e+09,1662600000
3,4,North Lanarkshire,S12000050,1993,1606.71,998.36,1.253500e+09,1547600000
4,5,Somerset,E06000066,1993,6630.33,4119.90,2.410300e+09,2958200000

================================================================================
File: region_traffic_by_road_type.csv
================================================================================
Preview shape: (5, 9)
Columns:
['year', 'region_id', 'region_name', 'region_ons_code', 'road_category_id', 'road_category_name', 'link_length_km', 'link_length_miles', 'all_motor_vehicles']

,year,region_id,region_name,region_ons_code,road_category_id,road_category_name,link_length_km,link_length_miles,all_motor_vehicles
0,1993,1,South West,E12000009,1,TM,301.34,187.24,3.465800e+09
1,1993,1,South West,E12000009,3,TA,993.59,617.39,3.484700e+09
2,1993,1,South West,E12000009,4,PA,3874.92,2407.76,7.794000e+09
3,1993,1,South West,E12000009,5,M,43581.70,27080.41,9.112000e+09
4,1993,2,East Midlands,E12000004,1,TM,178.61,110.98,2.736700e+09

================================================================================
File: region_traffic_by_vehicle_type.csv
================================================================================
Preview shape: (5, 13)
Columns:
['year', 'region_id', 'region_name', 'region_ons_code', 'link_length_km', 'link_length_miles', 'pedal_cycles', 'two_wheeled_motor_vehicles', 'cars_and_taxis', 'buses_and_coaches', 'LGVs', 'all_HGVs', 'all_motor_vehicles']

,year,region_id,region_name,region_ons_code,link_length_km,link_length_miles,pedal_cycles,two_wheeled_motor_vehicles,cars_and_taxis,buses_and_coaches,LGVs,all_HGVs,all_motor_vehicles
0,1993,1,South West,E12000009,48751.55,30292.81,228000000.0,289900000,1.967430e+10,245000000.0,2.351700e+09,1295600000,23856600000
1,1993,2,East Midlands,E12000004,30681.75,19064.76,199700000.0,172800000,1.620020e+10,190100000.0,2.082200e+09,1647100000,20292400000
2,1993,3,Scotland,S92000003,58532.65,36370.50,147300000.0,126400000,1.767760e+10,334300000.0,2.231000e+09,1339900000,21709300000
3,1993,4,Wales,W92000004,32543.50,20221.59,81700000.0,104600000,1.127880e+10,156300000.0,1.452700e+09,735200000,13727600000
4,1993,5,North West,E12000002,35952.60,22339.91,251400000.0,199200000,2.373000e+10,339800000.0,2.801800e+09,1834400000,28905200000

## Inspect ODS Road Freight Files

This section checks the ODS files downloaded from GOV.UK road freight statistics tables.

ODS files can contain multiple sheets and may have title/header rows before the actual data table.

In [9]:
# Inspect ODS files

ods_files = [file for file in raw_files if file.suffix.lower() == ".ods"]

print("ODS files found:", len(ods_files))

for file in ods_files:
    print("\n" + "=" * 80)
    print("File:", file.name)
    print("=" * 80)
    
    try:
        excel_file = pd.ExcelFile(file, engine="odf")
        print("Sheet names:")
        print(excel_file.sheet_names)
        
    except Exception as error:
        print("Could not open ODS file:", file.name)
        print("Error:", error)

ODS files found: 4

================================================================================
File: rfs0101.ods
================================================================================
Sheet names:
['Cover_sheet', 'Table_of_contents', 'RFS0101_Quarterly', 'RFS0101_Annual', 'RFS0101_Notes']

================================================================================
File: rfs0121.ods
================================================================================
Sheet names:
['Cover_sheet', 'Table_of_contents', 'RFS0121_GoodsLifted', 'RFS0121_GoodsMoved', 'RFS0121_Notes']

================================================================================
File: rfs0122.ods
================================================================================
Sheet names:
['Cover_sheet', 'Table_of_contents', 'RFS0122_GoodsLifted', 'RFS0122_GoodsMoved', 'RFS0122_Notes']

================================================================================
File: rfs0125.ods
================================================================================
Sheet names:
['Cover_sheet', 'RFS0125', 'RFS0125_Notes']

In [10]:
# Preview the first sheet from each ODS file

for file in ods_files:
    print("\n" + "=" * 80)
    print("File:", file.name)
    print("=" * 80)
    
    try:
        excel_file = pd.ExcelFile(file, engine="odf")
        first_sheet = excel_file.sheet_names[0]
        
        print("Previewing sheet:", first_sheet)
        
        df_ods_preview = pd.read_excel(
            file,
            sheet_name=first_sheet,
            engine="odf",
            header=None,
            nrows=15
        )
        
        display(df_ods_preview)
        
    except Exception as error:
        print("Could not preview ODS file:", file.name)
        print("Error:", error)

================================================================================
File: rfs0101.ods
================================================================================
Previewing sheet: Cover_sheet

                                                    0
0   Goods moved, goods lifted and vehicle kilometr...
1   This workbook contains 2 data tables with an a...
2                     Author: Road Freight Statistics
3   Source: Domestic road haulage survey (Great Br...
4                             Road Freight Statistics
5                                    Methodology note
6                               Notes and definitions
7                              Last updated: May 2026
8                            Next update: Summer 2026
9   The statistics presented in this spreadsheet w...
10                                           Contact
11                       roadfreight.stats@dft.gov.uk

================================================================================
File: rfs0121.ods
================================================================================
Previewing sheet: Cover_sheet

                                                    0
0   Goods lifted and goods moved by region and cou...
1   This workbook contains 2 data tables with an a...
2                     Author: Road Freight Statistics
3   Source: Domestic road haulage survey (Great Br...
4                             Road Freight Statistics
5                                    Methodology note
6                               Notes and definitions
7                              Last updated: May 2026
8                            Next update: Spring 2027
9   The statistics presented in this spreadsheet w...
10                                            Contact
11                       roadfreight.stats@dft.gov.uk

================================================================================
File: rfs0122.ods
================================================================================
Previewing sheet: Cover_sheet

                                                    0
0   Goods lifted and goods moved by region and cou...
1   This workbook contains 2 data tables with an a...
2                     Author: Road Freight Statistics
3   Source: Domestic road haulage survey (Great Br...
4                             Road Freight Statistics
5                                    Methodology note
6                               Notes and definitions
7                              Last updated: May 2026
8                            Next update: Spring 2027
9   The statistics presented in this spreadsheet w...
10                                            Contact
11                       roadfreight.stats@dft.gov.uk

================================================================================
File: rfs0125.ods
================================================================================
Previewing sheet: Cover_sheet

                                                    0
0   Percentage empty running and loading factor by...
1   This workbook contains 1 data table with an ac...
2                     Author: Road Freight Statistics
3   Source: Domestic road haulage survey (Great Br...
4                             Road Freight Statistics
5                                    Methodology note
6                               Notes and definitions
7                              Last updated: May 2026
8                            Next update: Spring 2027
9   The statistics presented in this spreadsheet w...
10                                            Contact
11                       roadfreight.stats@dft.gov.uk

In [11]:
# Create ODS sheet inventory

ods_sheet_inventory = []

for file in ods_files:
    try:
        excel_file = pd.ExcelFile(file, engine="odf")
        
        for sheet_name in excel_file.sheet_names:
            ods_sheet_inventory.append({
                "file_name": file.name,
                "sheet_name": sheet_name
            })
            
    except Exception as error:
        ods_sheet_inventory.append({
            "file_name": file.name,
            "sheet_name": f"ERROR: {error}"
        })

ods_sheet_inventory_df = pd.DataFrame(ods_sheet_inventory)

ods_sheet_inventory_df

      file_name           sheet_name
0   rfs0101.ods          Cover_sheet
1   rfs0101.ods    Table_of_contents
2   rfs0101.ods    RFS0101_Quarterly
3   rfs0101.ods       RFS0101_Annual
4   rfs0101.ods        RFS0101_Notes
5   rfs0121.ods          Cover_sheet
6   rfs0121.ods    Table_of_contents
7   rfs0121.ods  RFS0121_GoodsLifted
8   rfs0121.ods   RFS0121_GoodsMoved
9   rfs0121.ods        RFS0121_Notes
10  rfs0122.ods          Cover_sheet
11  rfs0122.ods    Table_of_contents
12  rfs0122.ods  RFS0122_GoodsLifted
13  rfs0122.ods   RFS0122_GoodsMoved
14  rfs0122.ods        RFS0122_Notes
15  rfs0125.ods          Cover_sheet
16  rfs0125.ods              RFS0125
17  rfs0125.ods        RFS0125_Notes

## Initial Data Understanding Notes

The downloaded Department for Transport files have been inspected at a raw structure level.

Initial checks completed:

- Listed all raw files
- Checked file extensions and file sizes
- Previewed CSV files
- Checked ODS workbook sheet names
- Previewed the first sheet of each ODS workbook
- Created an ODS sheet inventory

The next stage will focus on cleaning and preparing the most useful road freight and road traffic datasets for analysis.

Likely useful datasets include:

- Road freight goods lifted / goods moved / vehicle kilometres
- Regional freight movement tables
- Empty running and loading factor tables
- Regional traffic by vehicle type
- Regional traffic by road type
- Local authority traffic by vehicle class